apiVersion: v1
kind: Service
metadata:
  name: nodeport-svc
  labels:  # Corrected typo
    env: demo
spec:
  selector:
    env: demo
  type: NodePort
  ports:
  - nodePort: 30001  # Corrected field name
    port: 80
    targetPort: 80

