apiVersion: v1
kind: ReplicationController
metadata:
  name: nginx-rc
  labels:
    env: demo
spec:
  template: # the pod template that gets deployed 
    metadata:
      name: nginx
      labels:
        env: demo
    spec:
      containers:
      - name: nginx-container
        image: nginx
        ports:
        - containerPort: 80
  replicas: 3

~                                                                                                                                                                                                           
~       
